name: Keep Server and Database Alive

on:
  schedule:
    - cron: "*/45 * * * *"  
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    env:  # Set environment variable globally for the job
      SQLALCHEMY_DATABASE_URL: ${{ secrets.SQLALCHEMY_DATABASE_URL }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Send ping to server
        run: |
          curl -X GET https://gamedx.onrender.com/

      - name: Echo SQLALCHEMY_DATABASE_URL
        run: echo $SQLALCHEMY_DATABASE_URL

      - name: Keep the database alive
        run: |
          python3 ./keepalive.py
