name: Keep Server and Database Alive

on:
  schedule:
    - cron: "*/45 * * * *"  
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Send ping to server
        run: |
          curl -X GET https://gamedx.onrender.com/

      - name: Test database connection
        run: |
          python -c "
          import psycopg2
          import os
          conn = psycopg2.connect(os.getenv('SQLALCHEMY_DATABASE_URL'))
          print('Connected to DB successfully')
          "


      - name: Keep the database alive
        env:
          SQLALCHEMY_DATABASE_URL: ${{ secrets.SQLALCHEMY_DATABASE_URL }}
        run: |
          python3 ./keepalive.py
